import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

import NavBar from './components/NavBar/index';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body
        className={
          inter.className +
          ' overflow-hiddenn flex h-full w-full flex-col bg-bg-mobile bg-cover font-mono text-branco-padrao lg:h-screen lg:flex-row lg:bg-bg-original'
        }
      >
        <Toaster />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
